package com.progmatic.snowball.entity;

// Generated 19.05.2015 13:37:53 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Action generated by hbm2java
 */
//@Entity
//@Table(name = "action", schema = "public")
//@SequenceGenerator(name="action_id_seq", sequenceName="action_id_seq", allocationSize=1)
//@Restrict
public class Action implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private String object;
	private String action;
	private String objname;
	private String actname;
	private Set<Role> roles = new HashSet<Role>(0);

	public Action() {
	}

	public Action(long id, String object) {
		this.id = id;
		this.object = object;
	}

	public Action(long id, String object, String action, String objname,
			String actname, Set<Role> roles) {
		this.id = id;
		this.object = object;
		this.action = action;
		this.objname = objname;
		this.actname = actname;
		this.roles = roles;
	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
  	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="action_id_seq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	//@Column(name = "object", nullable = false, length = 100)
	//@NotNull
	//@Size(max = 100)
	public String getObject() {
		return this.object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	//@Column(name = "action", length = 100)
	//@Size(max = 100)
	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

	//@Column(name = "objname", length = 100)
	//@Size(max = 100)
	public String getObjname() {
		return this.objname;
	}

	public void setObjname(String objname) {
		this.objname = objname;
	}

	//@Column(name = "actname", length = 100)
	//@Size(max = 100)
	public String getActname() {
		return this.actname;
	}

	public void setActname(String actname) {
		this.actname = actname;
	}

	//@ManyToMany(fetch = FetchType.LAZY)
	//@JoinTable(name = "role_action", schema = "public", joinColumns = { @JoinColumn(name = "action_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
