package com.progmatic.snowball.entity;

// Generated 30.11.2015 19:37:03 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * LayerSvg generated by hbm2java
 */
//@Entity
//@Table(name = "layer_svg", schema = "public", uniqueConstraints = @UniqueConstraint(name = "layer_svg_area_id_name_part_type_unique", columnNames = {
//		"ski_area_id", "name", "part", "type" }))
//@SequenceGenerator(name="layer_svg_id_seq", sequenceName="layer_svg_id_seq", allocationSize=1)
//@Restrict
public class LayerSvg implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private String name;
	private String svgFilename;
	private String schemeData;
	private String info;
	private Integer part;
	private int status;
	private Integer type;
	private Set<LayerSvgSegment> layerSvgSegments = new HashSet<LayerSvgSegment>(0);
	private Long skiAreaId;
	private SkiArea skiArea;

	public LayerSvg() {
	}

	public LayerSvg(int id, String name, String svgFilename,
			int status) {
		this.id = id;
		this.name = name;
		this.svgFilename = svgFilename;
		this.status = status;
	}

	public LayerSvg(int id, String name, String svgFilename, String schemeData,
			String info, Integer part, int status, Long skiAreaId, SkiArea skiArea,
			Integer type, Set<LayerSvgSegment> layerSvgSegments) {
		this.id = id;
		this.name = name;
		this.svgFilename = svgFilename;
		this.schemeData = schemeData;
		this.info = info;
		this.part = part;
		this.status = status;
		this.type = type;
		this.layerSvgSegments = layerSvgSegments;
		this.skiAreaId = skiAreaId;
		this.skiArea = skiArea;
	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
  	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="layer_svg_id_seq")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	//@Column(name = "name", nullable = false, length = 125)
	//@NotNull
	//@Size(max = 125)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	//@Column(name = "ski_area_id", insertable = false, updatable = false)
	public Long getSkiAreaId() {
		return this.skiAreaId;
	}

	public void setSkiAreaId(Long skiAreaId) {
		this.skiAreaId = skiAreaId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "ski_area_id")
	public SkiArea getSkiArea() {
		return this.skiArea;
	}

	public void setSkiArea(SkiArea skiArea) {
		this.skiArea = skiArea;
	}

	//@Column(name = "svg_filename", nullable = false, length = 125)
	//@NotNull
	//@Size(max = 125)
	public String getSvgFilename() {
		return this.svgFilename;
	}

	public void setSvgFilename(String svgFilename) {
		this.svgFilename = svgFilename;
	}

	//@Column(name = "scheme_data")
	public String getSchemeData() {
		return this.schemeData;
	}

	public void setSchemeData(String schemeData) {
		this.schemeData = schemeData;
	}

	//@Column(name = "info")
	public String getInfo() {
		return this.info;
	}

	public void setInfo(String info) {
		this.info = info;
	}

	//@Column(name = "part")
	public Integer getPart() {
		return this.part;
	}

	public void setPart(Integer part) {
		this.part = part;
	}

	//@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	//@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "layerSvg")
	public Set<LayerSvgSegment> getLayerSvgSegments() {
		return this.layerSvgSegments;
	}

	public void setLayerSvgSegments(Set<LayerSvgSegment> layerSvgSegments) {
		this.layerSvgSegments = layerSvgSegments;
	}
	
	public String stringType()
	{
		String result = "";
		
		if (this.getType() != null)
		{
			switch (this.getType())
			{
			case 1:
				result = "piste";
				break;
			case 2:
				result = "lift";
				break;
			case 3:
				result = "POI";
				break;
			}
		}
		
		return result;
	}
}
