package com.progmatic.snowball.entity;

// Generated 30.11.2015 19:37:03 by Hibernate Tools 3.4.0.CR1

/**
 * LayerSvgSegments generated by hbm2java
 */
//@Entity
//@Table(name = "layer_svg_segments", schema = "public")
//@SequenceGenerator(name="layer_svg_segment_id_seq", sequenceName="layer_svg_segment_id_seq", allocationSize=1)
//@Restrict
public class LayerSvgSegment implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int id;
	private long layerSvgId;
	private LayerSvg layerSvg;
	private int segment;
	private String schemeData;
	private Long layerDataId;
	private LayerData layerData;
	private int status;
	private String log;

	public LayerSvgSegment() {
	}

	public LayerSvgSegment(int id, long layerSvgId, LayerSvg layerSvg, int segment, int status) {
		this.id = id;
		this.layerSvgId = layerSvgId;
		this.segment = segment;
		this.status = status;
		this.layerSvg = layerSvg;
	}

	public LayerSvgSegment(int id, long layerSvgId, LayerSvg layerSvg, int segment,
			String schemeData, Long layerDataId, LayerData layerData, int status, String log) {
		this.id = id;
		this.layerSvgId = layerSvgId;
		this.segment = segment;
		this.schemeData = schemeData;
		this.layerDataId = layerDataId;
		this.status = status;
		this.log = log;
		this.layerSvg = layerSvg;
		this.layerData = layerData;

	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
  	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="layer_svg_segment_id_seq")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	//@Column(name = "layer_svg_id", insertable = false, updatable = false)
	public long getLayerSvgId() {
		return this.layerSvgId;
	}

	public void setLayerSvgId(long layerSvgId) {
		this.layerSvgId = layerSvgId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "layer_svg_id", nullable = false)
	//@NotNull
	public LayerSvg getLayerSvg() {
		return this.layerSvg;
	}

	public void setLayerSvg(LayerSvg layerSvg) {
		this.layerSvg = layerSvg;
	}

	//@Column(name = "segment", nullable = false)
	public int getSegment() {
		return this.segment;
	}

	public void setSegment(int segment) {
		this.segment = segment;
	}

	//@Column(name = "scheme_data")
	public String getSchemeData() {
		return this.schemeData;
	}

	public void setSchemeData(String schemeData) {
		this.schemeData = schemeData;
	}

	//@Column(name = "layer_data_id")
	public Long getLayerDataId() {
		return this.layerDataId;
	}

	public void setLayerDataId(Long layerDataId) {
		this.layerDataId = layerDataId;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "layer_data_id", insertable = false, updatable = false)
	public LayerData getLayerData() {
		return this.layerData;
	}

	public void setLayerData(LayerData layerData) {
		this.layerData = layerData;
	}

	//@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	//@Column(name = "log")
	public String getLog() {
		return this.log;
	}

	public void setLog(String log) {
		this.log = log;
	}

	public String stringStatus()
	{
		String result = "";
		
		switch (this.getStatus())
		{
		case 0:
			result = "Not linked segment";
			break;
		case 1:
			result = "Linked segment";
			break;
		case 2:
			result = "Wrong data";
			break;
		}
		
		return result;
	}
}
