package com.progmatic.snowball.entity;

// Generated 17.09.2015 1:49:53 by Hibernate Tools 3.4.0.CR1

/**
 * LayerDataInZoom generated by hbm2java
 */
//@Entity
//@Table(name = "layer_data_in_zoom", schema = "public")
//@SequenceGenerator(name="layer_data_in_zoom_id_seq", sequenceName="layer_data_in_zoom_id_seq", allocationSize=1)
//@Restrict
public class LayerDataInZoom implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private int zoomNum;
	private LayerData layerData;

	public LayerDataInZoom() {
	}

	public LayerDataInZoom(long id, int zoomNum) {
		this.id = id;
		this.zoomNum = zoomNum;
	}

	public LayerDataInZoom(long id, int zoomNum, LayerData layerData) {
		this.id = id;
		this.zoomNum = zoomNum;
		this.layerData = layerData;
	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
  	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="layer_data_in_zoom_id_seq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	//@Column(name = "zoom_num", nullable = false)
	public int getZoomNum() {
		return this.zoomNum;
	}

	public void setZoomNum(int zoomNum) {
		this.zoomNum = zoomNum;
	}

	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "layer_data_id", nullable = false)
	//@NotNull
	public LayerData getLayerData() {
		return this.layerData;
	}

	public void setLayerData(LayerData layerData) {
		this.layerData = layerData;
	}

}
