package com.progmatic.snowball.entity;

// Generated 23.06.2015 16:19:08 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * LayerType generated by hbm2java
 */
//@Entity
//@Table(name = "layer_type", schema = "public")
//@Restrict
public class LayerType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private int groupType;
	private String name;
	private Set<LayerData> layerDatas = new HashSet<LayerData>(0);

	public LayerType() {
	}

	public LayerType(long id, int groupType, String name,
			Set<LayerData> layerDatas) {
		this.id = id;
		this.groupType = groupType;
		this.name = name;
		this.layerDatas = layerDatas;
	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	//@Column(name = "group_type", nullable = false)
	public int getGroupType() {
		return this.groupType;
	}

	public void setGroupType(int groupType) {
		this.groupType = groupType;
	}

	//@Column(name = "name", nullable = false, length = 125)
	//@NotNull
	//@Size(max = 125)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	//@OneToMany(fetch = FetchType.LAZY, mappedBy = "layerType")
	public Set<LayerData> getLayerDatas() {
		return this.layerDatas;
	}

	public void setLayerDatas(Set<LayerData> layerDatas) {
		this.layerDatas = layerDatas;
	}

}
