package com.progmatic.snowball.entity;

// Generated 10.01.2016 21:08:01 by Hibernate Tools 3.4.0.CR1

import com.progmatic.snowball.utils.XmlParser;

/**
 * NodalPoint generated by hbm2java
 */
//@Entity
//@Table(name = "nodal_point", schema = "public")
//@SequenceGenerator(name="nodal_point_id_seq", sequenceName="nodal_point_id_seq", allocationSize=1)
//@Restrict
public class NodalPoint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private SkiArea skiArea;
	private long skiAreaId;
	private double latitude;
	private double longitude;
	private int altitude;
	private String transitionsFrom;
	private String transitionsTo;

	public NodalPoint() {
	}

	public NodalPoint(long id, long skiAreaId, SkiArea skiArea, double latitude,
			double longitude, int altitude) {
		this.id = id;
		this.skiAreaId = skiAreaId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.altitude = altitude;
		this.skiArea = skiArea;
	}

	public NodalPoint(long id, long skiAreaId, SkiArea skiArea, double latitude,
			double longitude, int altitude, String transitionsFrom, String transitionsTo) {
		this.id = id;
		this.skiAreaId = skiAreaId;
		this.skiArea = skiArea;
		this.latitude = latitude;
		this.longitude = longitude;
		this.altitude = altitude;
		this.transitionsFrom = transitionsFrom;
		this.transitionsTo = transitionsTo;
	}

	//@Id
	//@Column(name = "id", unique = true, nullable = false)
  	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="nodal_point_id_seq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	//@Column(name = "ski_area_id", insertable = false, updatable = false)
	public long getSkiAreaId() {
		return this.skiAreaId;
	}

	public void setSkiAreaId(long skiAreaId) {
		this.skiAreaId = skiAreaId;
	}
	
	//@ManyToOne(fetch = FetchType.LAZY)
	//@JoinColumn(name = "ski_area_id", nullable = false)
	//@NotNull
	public SkiArea getSkiArea() {
		return this.skiArea;
	}

	public void setSkiArea(SkiArea skiArea) {
		this.skiArea = skiArea;
	}
	

	//@Column(name = "latitude", nullable = false, precision = 17, scale = 17)
	//@NotNull
	public double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(double latitude) {
		this.latitude = latitude;
	}

	//@Column(name = "longitude", nullable = false, precision = 17, scale = 17)
	//@NotNull
	public double getLongitude() {
		return this.longitude;
	}
	public void setLongitude(double longitude) {
		this.longitude = longitude;
	}


	//@Column(name = "altitude", nullable = false, columnDefinition="integer default 0")
	//@NotNull
	public int getAltitude() {
		return this.altitude;
	}
	public void setAltitude(int altitude) {
		this.altitude = altitude;
	}

	//@Column(name = "transitions_from")
	public String getTransitionsFrom() {
		return this.transitionsFrom;
	}

	public void setTransitionsFrom(String transitionsFrom) {
		this.transitionsFrom = transitionsFrom;
	}

	//@Column(name = "transitions_to")
	public String getTransitionsTo() {
		return this.transitionsTo;
	}

	public void setTransitionsTo(String transitionsTo) {
		this.transitionsTo = transitionsTo;
	}
	
	public int transitionsFromCount()
	{
		return XmlParser.deSerializeIds(this.getTransitionsFrom()).length;
	}

	public int transitionsToCount()
	{
		return XmlParser.deSerializeIds(this.getTransitionsTo()).length;
	}
}
