package com.progmatic.snowball.entity;
// Generated 19.05.2015 13:37:53 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
//@Entity
//@Table(name="role", schema="public")
//@SequenceGenerator(name="role_id_seq", sequenceName="role_id_seq", allocationSize=1)
//@Restrict
public class Role  implements java.io.Serializable {


     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
     private String name;
     private Set<User> users = new HashSet<User>(0);
     private Set<Action> actions = new HashSet<Action>(0);

    public Role() {
    }

	
    public Role(long id, String name) {
        this.id = id;
        this.name = name;
    }
    public Role(long id, String name, Set<User> users, Set<Action> actions) {
       this.id = id;
       this.name = name;
       this.users = users;
       this.actions = actions;
    }
   
    //@Id 
    //@Column(name="id", unique=true, nullable=false)
  	//@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="role_id_seq")
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    
    //@Column(name="name", nullable=false, length=30)
    //@NotNull
    //@Size(max=30)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

//@ManyToMany(fetch=FetchType.LAZY)
    //@JoinTable(name="user_role", schema="public", joinColumns = { 
        //@JoinColumn(name="role_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        //@JoinColumn(name="user_id", nullable=false, updatable=false) })
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }

//@ManyToMany(fetch=FetchType.LAZY)
    //@JoinTable(name="role_action", schema="public", joinColumns = { 
        //@JoinColumn(name="role_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
        //@JoinColumn(name="action_id", nullable=false, updatable=false) })
    public Set<Action> getActions() {
        return this.actions;
    }
    
    public void setActions(Set<Action> actions) {
        this.actions = actions;
    }




}


