package com.progmatic.snowball.entity;

// Generated 18.07.2015 18:41:55 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Track generated by hbm2java
 */
//@Entity
//@Table(name = "track", schema = "public")
//@SequenceGenerator(name="track_id_seq", sequenceName="track_id_seq", allocationSize=1)
//@Restrict
public class Track implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long id;
	private Date name;
	private User user;
	//private Device device;
	private Set<TrackPoint> trackPoints = new HashSet<TrackPoint>(0);
	private double x1;
	private double x2;
	private double y1;
	private double y2;
	private String location;

	public Track()
	{
	}

	public Track(long id, Date name, User user, /*Device device,*/
			double x1, double x2, double y1, double y2 )
	{
		this.id = id;
		this.name = name;
		this.user = user;
//		this.device = device;
		this.x1 = x1;
		this.x2 = x2;
		this.y1 = y1;
		this.y2 = y2;
	}

	public Track(long id, Date name, User user, /*Device device,*/ Set<TrackPoint> trackPoints,
				double x1, double x2, double y1, double y2, String location){
		this.id = id;
		this.name = name;
		this.user = user;
		//this.device = device;
		this.trackPoints = trackPoints;
		this.x1 = x1;
		this.x2 = x2;
		this.y1 = y1;
		this.y2 = y2;
		this.location = location;
	}

//	@Id
//	@Column(name = "id", unique = true, nullable = false)
//  	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="track_id_seq")
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

//	@Temporal(TemporalType.TIMESTAMP)
//	@Column(name = "name", nullable = false, length = 15)
//	@NotNull
	public Date getName() {
		return this.name;
	}

	public void setName(Date name) {
		this.name = name;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "user_id", nullable = false)
//	@NotNull
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "device_id", nullable = false)
//	@NotNull
//	public Device getDevice() {
//		return this.device;
//	}
//
//	public void setDevice(Device device) {
//		this.device = device;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "track")
	public Set<TrackPoint> getTrackPoints() {
		return this.trackPoints;
	}

	public void setTrackPoints(Set<TrackPoint> trackPoints) {
		this.trackPoints = trackPoints;
	}
	
//	@Column(name = "x1", precision = 17, scale = 17, nullable = false)
	public double getX1()
	{
		return this.x1;
	}
	public void setX1(double x1)
	{
		this.x1 = x1;
	}
	
//	@Column(name = "x2", precision = 17, scale = 17, nullable = false)
	public double getX2()
	{
		return this.x2;
	}
	public void setX2(double x2)
	{
		this.x2 = x2;
	}

//	@Column(name = "y1", precision = 17, scale = 17, nullable = false)
	public double getY1()
	{
		return this.y1;
	}
	public void setY1(double y1)
	{
		this.y1 = y1;
	}
	
//	@Column(name = "y2", precision = 17, scale = 17, nullable = false)
	public double getY2()
	{
		return this.y2;
	}
	public void setY2(double y2)
	{
		this.y2 = y2;
	}
	
//	@Column(name = "location", insertable = false, updatable = false)
	public String getLocation()
	{
		if (this.location == null)
		{
			String result = "";
			result = "Undefined place";
			if (this.getTrackPoints().size() != 0)
			{
				List<TrackPoint> tracks = new ArrayList<TrackPoint>(this.getTrackPoints());

				Comparator<TrackPoint> comparator = new Comparator<TrackPoint>() 
				{
				    public int compare(TrackPoint tp1, TrackPoint tp2)
				    {
				    	return tp1.getTime().compareTo(tp2.getTime());
				    }
				};
				
				Collections.sort(tracks, comparator);

				TrackPoint tp = tracks.get(0);
				result = result + " (" + tp.getLatitude() + ", " + tp.getLongitude() + ")";
			}

			this.location = result;
		}
		return this.location;
	}
	
	public void setLocation (String location)
	{
		this.location = location;
	}
}
